import Head from "next/head";
import {Layout, HeroSection} from '../components'

export default function Home() {
  return (
    <div className="bg-black min-h-screen">
      <Head>
        <title>DOA-REALTOR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Layout>
          <HeroSection />
        </Layout>
      </div>
    </div>
  );
}
