import Head from "next/head";
import Image from "next/image";
import { homes } from "../../assets/data/homes.json";
import { Layout } from "../../components";

function importAll(r) {
    let images = {};
    r.keys().map((item, index) => {
        return (images[item.replace("./", "")] = r(item));
    });
    return images;
}

const images = importAll(
    require.context("../../assets/images", false, /\.(png|jpe?g|svg|gif)$/)
);

export default function HomeListing({ data, id }) {
    const frontImg = `home_front_${id}.jpeg`;
    const interiorImg = `home_interior_${id}.jpeg`;
    const bathImg = `home_bath_${id}.jpeg`;
    const floorplanImg = `home_floorplan_${id}.jpeg`;
    const floorplanAImg = `home_floorplan_${id}a.jpeg`;

    return (
        <div className="bg-black min-h-screen">
            <Head>
                <title>DAO-REALTOR</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-black min-h-screen items-center justify-center text-white">
                <Layout>
                    <div className="pb-5">
                        <div className="container flex flex-col items-center justify-center">
                            <div className="flex flex-row items-center justify-center py-2">
                                <div className="flex flex-wrap">
                                    <Image src={images[frontImg]} width={300} height={200} alt={data.title} />
                                    <Image src={images[interiorImg]} width={300} height={200} alt={data.title} />
                                    <Image src={images[bathImg]} width={300} height={200} alt={data.title} />
                                    <Image src={images[floorplanImg]} width={300} height={200} alt={data.title} />
                                    <Image src={images[floorplanAImg]} width={300} height={200} alt={data.title} />
                                </div>
                                <div className="flex flex-col items-center justify-center px-4 py-4">
                                    <h2 className="text-2xl font-bold text-center">{data.title}</h2>
                                    <div className="py-4">
                                        <p className="text-center">{data.address}</p>
                                        <p className="text-center">{data.city}, {data.state} {data.zip}</p>
                                        <p className="text-center">{data.beds} beds, {data.baths} baths</p>
                                        <p className="text-center">{data.area} sqft</p>
                                        <p className="text-center">{data.price}</p>
                                    </div>
                                    <div>
                                        <button type="button" className="bg-[#2952e3] block rounded-full cursor-pointer px-2 py-1 hover:bg-[#2546bd]">
                                            Validate
                                        </button>
                                    </div>
                                    <div>
                                        <button type="button" className="bg-[#2952e3] block rounded-full cursor-pointer px-2 py-1 hover:bg-[#2546bd]">
                                            Invest
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr className="bg-gray-400 border-t w-1/2" />
                        </div>
                    </div>


                </Layout>
            </div>
        </div>
    );
}

export async function getServerSideProps({ params }) {
    const id = params.id;
    const data = homes[id];
    return { props: { data, id } }
}