import Head from "next/head";
import Image from "next/image";
import { homes } from "../../assets/data/homes.json";
import { Layout } from "../../components";
import { BiCurrentLocation } from "react-icons/bi";
import { IoIosBed } from "react-icons/io";
import { FaBath } from "react-icons/fa";
import { BsBoundingBoxCircles } from "react-icons/bs";

function importAll(r) {
  let images = {};
  r.keys().map((item, index) => {
    return (images[item.replace("./", "")] = r(item));
  });
  return images;
}

const images = importAll(
  require.context("../../assets/images", false, /\.(png|jpe?g|svg|gif)$/)
);

export default function HomeListing({ data, id }) {
  const frontImg = `home_front_${id}.jpeg`;
  const interiorImg = `home_interior_${id}.jpeg`;
  const bathImg = `home_bath_${id}.jpeg`;
  const floorplanImg = `home_floorplan_${id}.jpeg`;
  const floorplanAImg = `home_floorplan_${id}a.jpeg`;

  return (
    <div className="bg-black min-h-screen">
      <Head>
        <title>DAO-REALTOR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black min-h-screen items-center justify-center text-white">
        <Layout>
          <div className="pb-5">
            <div className="container flex flex-col items-center ">
              <div className="">
                <section class="overflow-hidden">
                  <div class="container px-5 py-2 mx-auto lg:pt-24 lg:px-32">
                    <div class="flex flex-wrap -m-1 md:-m-2">
                      <div class="flex flex-wrap w-1/2">
                        <div class="w-full p-1 md:p-2">
                          <Image
                            src={images[frontImg]}
                            width={1000}
                            height={680}
                            alt={data.title}
                            className="block object-cover object-center w-full h-full rounded-tl-2xl rounded-bl-2xl opacity-100 hover:opacity-90 cursor-pointer"
                          />
                        </div>
                      </div>
                      <div class="flex flex-wrap w-1/2">
                        <div class="w-1/2 p-1 md:p-2">
                          <Image
                            src={images[interiorImg]}
                            width={300}
                            height={200}
                            alt={data.title}
                            className="block object-cover object-center w-full h-full opacity-100 hover:opacity-90 cursor-pointer"
                          />
                        </div>
                        <div class="w-1/2 p-1 md:p-2">
                          <Image
                            src={images[bathImg]}
                            width={300}
                            height={200}
                            alt={data.title}
                            className="block object-cover object-center w-full h-full rounded-tr-2xl opacity-100 hover:opacity-90 cursor-pointer"
                          />
                        </div>
                        <div class="w-1/2 p-1 md:p-2">
                          <Image
                            src={images[floorplanImg]}
                            width={300}
                            height={200}
                            alt={data.title}
                            className="block object-cover object-center w-full h-full  opacity-100 hover:opacity-90 cursor-pointer"
                          />
                        </div>
                        <div class="w-1/2 p-1 md:p-2">
                          <Image
                            src={images[floorplanAImg]}
                            width={300}
                            height={200}
                            alt={data.title}
                            className="block object-cover object-center w-full h-full rounded-br-2xl opacity-100 hover:opacity-90 cursor-pointer"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <div className="flex flex-col  px-4 py-4 ml-28">
                  <h2 className="text-2xl font-bold">{data.title}</h2>
                  <div className="flex items-center ">
                    <div className="pb-4">
                      <p className="text-xl mb-2 text-blue-600 mt-2">
                        {data.price}
                      </p>
                      <div className="flex items-center text-xl mb-2">
                        <BiCurrentLocation className="text-red-500" />
                        <p className="ml-3">{data.address}</p>
                        <p className="ml-1">
                          {data.city}, {data.state} {data.zip}
                        </p>
                      </div>
                      <div className="flex items-center text-xl">
                        <div className="flex items-center">
                          <IoIosBed />
                          <p className="ml-2">{data.beds} beds</p>
                        </div>
                        <div className="flex items-center ml-6">
                          <FaBath />
                          <p className="ml-2">{data.baths} baths</p>
                        </div>
                        <div className="flex items-center ml-6">
                          <BsBoundingBoxCircles />
                          <p className="ml-2">{data.area} </p>
                        </div>
                      </div>
                      <p className="flex mt-4">
                        {Array(data.rating)
                          .fill()
                          .map((_, i) => (
                            <p>⭐</p>
                          ))}
                      </p>
                    </div>
                    <div className="ml-14">
                      <button
                        type="button"
                        className="bg-[#2952e3] block rounded-full cursor-pointer px-8 py-2 mb-5 hover:bg-[#2546bd]"
                      >
                        Validate
                      </button>
                      <button
                        type="button"
                        className="bg-[#2952e3] block rounded-full cursor-pointer px-10 py-2 hover:bg-[#2546bd]"
                      >
                        Invest
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <hr className="bg-gray-400 border-t w-1/2" />
            </div>
          </div>
        </Layout>
      </div>
    </div>
  );
}

export async function getServerSideProps({ params }) {
  const id = params.id;
  const data = homes[id];
  return { props: { data, id } };
}
